version: v1.0
name: docker-pull
description: Pull all the necessary Docker images from the B2P registry
jobs:
  - job: Pull the Docker images
    steps:
      - Docker login:
          password: '{{.cds.env.DOCKER_REGISTRY_PASSWORD}}'
          registry: '{{.cds.env.DOCKER_REGISTRY}}'
          username: '{{.cds.env.DOCKER_REGISTRY_USERNAME}}'
      - name: List Docker images
        script:
          - '# List our own Docker images'
          - docker images | grep {{.cds.env.DOCKER_REGISTRY_PREFIX}}
      - name: Pull Docker images
        script:
          - '# Pulling the main services images'
          - echo "Pulling {{.cds.env.DOCKER_REGISTRY}}{{.cds.env.DOCKER_REGISTRY_PREFIX}}epr-backend_db:0"
          - docker pull {{.cds.env.DOCKER_REGISTRY}}{{.cds.env.DOCKER_REGISTRY_PREFIX}}epr-backend_db:{{.cds.env.IMAGE_TAG_DB}}
          - docker pull {{.cds.env.DOCKER_REGISTRY}}{{.cds.env.DOCKER_REGISTRY_PREFIX}}epr-backend_nginx:{{.cds.env.IMAGE_TAG_NGINX}}
          - docker pull {{.cds.env.DOCKER_REGISTRY}}{{.cds.env.DOCKER_REGISTRY_PREFIX}}epr-backend_mailer:{{.cds.env.IMAGE_TAG_MAILER}}
          - docker pull {{.cds.env.DOCKER_REGISTRY}}{{.cds.env.DOCKER_REGISTRY_PREFIX}}epr-backend_php:{{.cds.env.IMAGE_TAG_PHP}}
      - Docker logout:
          registry: '{{.cds.env.DOCKER_REGISTRY}}'
      - name: List Docker images
        script:
          - '# List our own Docker images'
          - docker images | grep {{.cds.env.DOCKER_REGISTRY_PREFIX}}
    requirements:
      - binary: docker
      - model: docker-compose-git-bash
